import { useEffect, useState } from "react";
export type HomeArea = { town: string; city: string; latitude: number; longitude: number };
export const homeAreaKey = (userId: string) => `artility-home-area:${userId}`;
export default function HomeAreaSettings({ userId }: { userId: string }) {
  const [town, setTown] = useState(""); const [city, setCity] = useState(""); const [point, setPoint] = useState<{ latitude: number; longitude: number } | null>(null); const [message, setMessage] = useState("");
  useEffect(() => { const saved = localStorage.getItem(homeAreaKey(userId)); if (saved) { const area = JSON.parse(saved) as HomeArea; setTown(area.town); setCity(area.city); setPoint(area); } }, [userId]);
  function locate() { navigator.geolocation?.getCurrentPosition((p) => { setPoint({ latitude: Math.round(p.coords.latitude * 100) / 100, longitude: Math.round(p.coords.longitude * 100) / 100 }); setMessage("Approximate map point selected."); }, () => setMessage("Location was unavailable."), { enableHighAccuracy: false }); }
  function save(e: React.FormEvent) { e.preventDefault(); if (!point) return setMessage("Choose an approximate map point first."); localStorage.setItem(homeAreaKey(userId), JSON.stringify({ town, city, ...point })); setMessage("Saved. Explore will start here next time."); }
  return <section className="home-area-settings"><span className="eyebrow">HOME AREA</span><h2>Start Explore from home</h2><p className="home-area-intro">Private to this device · rounded to about 1 km.</p><form onSubmit={save}><div className="home-area-fields"><label>Town<input value={town} onChange={(e) => setTown(e.target.value)} required /></label><label>City<input value={city} onChange={(e) => setCity(e.target.value)} required /></label></div><div className="home-area-actions"><button type="button" className="secondary-button" onClick={locate}>Choose map point</button><button className="primary-button">Save home area</button></div></form>{message && <p className="home-area-message" role="status">{message}</p>}</section>;
}
